version: "3.7"
services:
  master-v1:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-issueV0.py --master -H http://host.docker.internal:8080

  worker-v1:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-issueV0.py --worker --master-host master-v1

  master-async-v1:
    image: locustio/locust
    ports:
      - "8090:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-issue-asyncV1.py --master -H http://host.docker.internal:8080

  worker-async-v1:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-issue-asyncV1.py --worker --master-host master-async-v1

  master-async-v2:
    image: locustio/locust
    ports:
      - "8091:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-issue-asyncV2.py --master -H http://host.docker.internal:8080

  worker-async-v2:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-issue-asyncV2.py --worker --master-host master-async-v2

  master-async-v3:
    image: locustio/locust
    ports:
      - "8092:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-issue-asyncV3.py --master -H http://host.docker.internal:8080

  worker-async-v3:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile-issue-asyncV3.py --worker --master-host master-async-v3
